name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ${{matrix.runs-on}}

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test
        env:
          CI: true
